import type { HomeAssistant } from "./types";

type Dict = Record<string, string>;

const en: Dict = {
  occupied: "Occupied",
  clear: "Clear",
  motion: "Motion",
  no_motion: "No motion",
  door_open: "{n} door open",
  doors_open: "{n} doors open",
  doors_closed: "Doors closed",
  window_open: "{n} window open",
  windows_open: "{n} windows open",
  windows_closed: "Windows closed",
  cover_open: "{n} cover open",
  covers_open_n: "{n} covers open",
  covers_closed: "Covers closed",
  lock_unlocked: "{n} unlocked",
  locks_locked: "Locked",
  light_on: "{n} light on",
  lights_on_n: "{n} lights on",
  lights_off_all: "Lights off",
  fan_on: "{n} fan on",
  fans_on_n: "{n} fans on",
  fans_off_all: "Fans off",
  media_playing: "Playing",
  media_idle: "Media idle",
  climate_heating: "Heating",
  climate_cooling: "Cooling",
  climate_drying: "Drying",
  climate_fan: "Fan",
  climate_idle: "Idle",
  climate_off: "Climate off",
  alert: "Alert",
  alerts_n: "{n} alerts",
  battery_low: "{n} low battery",
  batteries_low: "{n} low batteries",
  for: "for {t}",
  since_now: "just now",
  area_not_found: "Area \"{area}\" was not found.",
  no_label_match: "No entity in this area has the label {labels}. Add it in Settings → Areas, labels & zones → Labels.",
  pick_area: "Pick an area in the card editor.",
  switch_on: "{n} switch on",
  switches_on_n: "{n} switches on",
  switches_off_all: "Switches off",
  turn_all_on: "All on",
  turn_all_off: "All off",
  open_all: "Open all",
  close_all: "Close all",
  pause_all: "Pause all",
  n_of_m_active: "{n} of {m} active",
  close: "Close",
  toggle_light: "Toggle {name}",
  ed_section_labels: "Filter by labels",
  ed_label_include: "Only show entities with these labels",
  ed_label_exclude: "Hide entities with these labels",
  ed_label_match: "An entity needs",
  ed_label_match_any: "At least one of the labels",
  ed_label_match_all: "All of the labels",
  ed_label_from_device: "Also use the device's labels",
  ed_main_light: "Main light (default: auto-detect)",
  ed_link_main_light: "Area icon toggles the main light",
  ed_top_groups: "First row (the rest go in the second row)",
  ed_color_temp_low: "Cold temperature color",
  ed_color_temp_high: "Warm temperature color",
  ed_color_hum_low: "Dry air color",
  ed_color_hum_high: "Humid air color",
  g_switches: "Switches & plugs",
  // presets
  preset_lights_toggle: "Lights",
  preset_lights_on: "Lights on",
  preset_lights_off: "Lights off",
  preset_covers_open: "Open covers",
  preset_covers_close: "Close covers",
  preset_fans_off: "Fans off",
  preset_media_stop: "Stop media",
  preset_vacuum_area: "Vacuum",
  preset_everything_off: "All off",
  confirm_vacuum: "Send the vacuum to clean {area}?",
  confirm_everything_off: "Turn off everything in {area}?",
  // editor
  ed_area: "Area",
  ed_name: "Name",
  ed_icon: "Icon",
  ed_color: "Accent color",
  ed_layout: "Layout",
  ed_layout_default: "Default",
  ed_layout_compact: "Compact",
  ed_show_picture: "Show area picture",
  ed_show_inactive: "Show inactive groups (e.g. \"Windows closed\")",
  ed_section_climate: "Climate & sensors",
  ed_section_status: "Status & alerts",
  ed_section_interactions: "Card interactions",
  ed_section_actions: "Quick actions",
  ed_temperature_entity: "Temperature sensor (default: area setting or median)",
  ed_humidity_entity: "Humidity sensor (default: area setting or median)",
  ed_sensor_classes: "Extra sensor readings",
  ed_comfort_temp_min: "Comfort temperature min",
  ed_comfort_temp_max: "Comfort temperature max",
  ed_comfort_hum_min: "Comfort humidity min",
  ed_comfort_hum_max: "Comfort humidity max",
  ed_groups: "Status groups",
  ed_alert_classes: "Alert device classes",
  ed_presence_entities: "Presence entities (default: auto-detect)",
  ed_exclude_entities: "Exclude entities",
  ed_battery_threshold: "Low battery threshold (%)",
  ed_tap_action: "Tap action",
  ed_hold_action: "Hold action",
  ed_double_tap_action: "Double tap action",
  ed_preset: "Preset",
  ed_preset_none: "Custom",
  ed_entity: "Entity",
  ed_add_action: "Add quick action",
  ed_remove: "Remove",
  ed_move_up: "Move up",
  ed_move_down: "Move down",
  ed_action_n: "Action {n}",
  ed_vacuum_hint: "Pick the vacuum entity. Uses vacuum.clean_area (HA 2026.3+), so map the vacuum's segments to areas first.",
  room_attention: "Needs attention",
  room_status: "Presence & openings",
  room_sensors: "Sensors",
  room_other: "Other",
  room_search: "Search this room",
  room_clear_search: "Clear search",
  room_show_more: "Show {n} more",
  room_show_less: "Show less",
  room_no_results: "Nothing matches “{q}”",
  room_empty: "No entities to show in this room.",
  reason_low_battery: "Low battery",
  reason_unavailable: "Unavailable",
  ed_room_popup: "Open the room popup when the card is tapped",
  // groups
  g_presence: "Presence",
  g_motion: "Motion",
  g_doors: "Doors",
  g_windows: "Windows",
  g_covers: "Covers",
  g_locks: "Locks",
  g_lights: "Lights",
  g_fans: "Fans",
  g_media: "Media",
  g_climate: "Climate",
  g_alerts: "Safety alerts",
  g_batteries: "Batteries",
};

const el: Dict = {
  occupied: "Κατειλημμένο",
  clear: "Άδειο",
  motion: "Κίνηση",
  no_motion: "Χωρίς κίνηση",
  door_open: "{n} πόρτα ανοιχτή",
  doors_open: "{n} πόρτες ανοιχτές",
  doors_closed: "Πόρτες κλειστές",
  window_open: "{n} παράθυρο ανοιχτό",
  windows_open: "{n} παράθυρα ανοιχτά",
  windows_closed: "Παράθυρα κλειστά",
  cover_open: "{n} ρολό ανοιχτό",
  covers_open_n: "{n} ρολά ανοιχτά",
  covers_closed: "Ρολά κλειστά",
  lock_unlocked: "{n} ξεκλείδωτη",
  locks_locked: "Κλειδωμένο",
  light_on: "{n} φως αναμμένο",
  lights_on_n: "{n} φώτα αναμμένα",
  lights_off_all: "Φώτα σβηστά",
  fan_on: "{n} ανεμιστήρας",
  fans_on_n: "{n} ανεμιστήρες",
  fans_off_all: "Ανεμιστήρες off",
  media_playing: "Αναπαραγωγή",
  media_idle: "Media σε αναμονή",
  climate_heating: "Θέρμανση",
  climate_cooling: "Ψύξη",
  climate_drying: "Αφύγρανση",
  climate_fan: "Ανεμιστήρας",
  climate_idle: "Αδρανές",
  climate_off: "Κλιματισμός off",
  alert: "Συναγερμός",
  alerts_n: "{n} ειδοποιήσεις",
  battery_low: "{n} χαμηλή μπαταρία",
  batteries_low: "{n} χαμηλές μπαταρίες",
  for: "εδώ και {t}",
  since_now: "μόλις τώρα",
  area_not_found: "Ο χώρος \"{area}\" δεν βρέθηκε.",
  no_label_match: "Καμία οντότητα σε αυτόν τον χώρο δεν έχει την ετικέτα {labels}. Πρόσθεσέ την από Ρυθμίσεις → Χώροι, ετικέτες & ζώνες → Ετικέτες.",
  pick_area: "Επίλεξε χώρο στον επεξεργαστή της κάρτας.",
  switch_on: "{n} διακόπτης on",
  switches_on_n: "{n} διακόπτες on",
  switches_off_all: "Διακόπτες off",
  turn_all_on: "Όλα on",
  turn_all_off: "Όλα off",
  open_all: "Άνοιγμα όλων",
  close_all: "Κλείσιμο όλων",
  pause_all: "Παύση όλων",
  n_of_m_active: "{n} από {m} ενεργά",
  close: "Κλείσιμο",
  toggle_light: "Εναλλαγή {name}",
  g_switches: "Διακόπτες & πρίζες",
  preset_lights_toggle: "Φώτα",
  preset_lights_on: "Άναμμα φώτων",
  preset_lights_off: "Σβήσιμο φώτων",
  preset_covers_open: "Άνοιγμα ρολών",
  preset_covers_close: "Κλείσιμο ρολών",
  preset_fans_off: "Ανεμιστήρες off",
  preset_media_stop: "Stop media",
  preset_vacuum_area: "Σκούπισμα",
  preset_everything_off: "Όλα off",
  confirm_vacuum: "Να σκουπίσει η σκούπα τον χώρο {area};",
  confirm_everything_off: "Να σβήσουν όλα στον χώρο {area};",
  room_attention: "Χρειάζονται προσοχή",
  room_status: "Παρουσία & ανοίγματα",
  room_sensors: "Αισθητήρες",
  room_other: "Άλλα",
  room_search: "Αναζήτηση στον χώρο",
  room_clear_search: "Καθαρισμός αναζήτησης",
  room_show_more: "Εμφάνιση άλλων {n}",
  room_show_less: "Λιγότερα",
  room_no_results: "Κανένα αποτέλεσμα για «{q}»",
  room_empty: "Δεν υπάρχουν οντότητες για εμφάνιση σε αυτόν τον χώρο.",
  reason_low_battery: "Χαμηλή μπαταρία",
  reason_unavailable: "Μη διαθέσιμο",
  g_presence: "Παρουσία",
  g_motion: "Κίνηση",
  g_doors: "Πόρτες",
  g_windows: "Παράθυρα",
  g_covers: "Ρολά",
  g_locks: "Κλειδαριές",
  g_lights: "Φώτα",
  g_fans: "Ανεμιστήρες",
  g_media: "Media",
  g_climate: "Κλιματισμός",
  g_alerts: "Ειδοποιήσεις ασφαλείας",
  g_batteries: "Μπαταρίες",
};

const LANGS: Record<string, Dict> = { en, el };

export function localize(
  hass: HomeAssistant | undefined,
  key: string,
  vars: Record<string, string | number> = {}
): string {
  const lang = (hass?.locale?.language || hass?.language || "en").split("-")[0];
  let s = LANGS[lang]?.[key] ?? en[key] ?? key;
  for (const [k, v] of Object.entries(vars)) s = s.replace(`{${k}}`, String(v));
  return s;
}
